apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmfile-prophet
  namespace: argocd2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://github.com/mohamedhabas11/argo-previews.git
    targetRevision: HEAD
    plugin:
      name: helmfile
    # namespace: previews-test
  project: previews
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
