---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
spec:
  destination:
    server: https://kubernetes.default.svc
  project: previews
  source:
    path: .
    plugin:
      name: helmfile
    repoURL: https://github.com/mohamedhabas11/bla.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
